### ISSUE TITLE
修改建议：电脑不能联网时的 texlive 宏包更新

### ISSUE THREAD

**Issue by muzimuzhi** [OsbertWang/install-latex#10]
目前描述（共有四份，这里摘取 windows 的那份）

https://github.com/OsbertWang/install-latex/blob/6649e8dc10b7a5164de34a93431b3f4e0c736dcb/chapter/windows.tex#L292-L298

需要修改的
1. 是 `tar.xz` 文档，文档里现作 `tar.gz`

需要补充的
1. 去哪里下载：https://ctan.org/tex-archive/systems/texlive/tlnet/archive （文件列表很长，需要时间加载）
1. 下载哪个文件
   - 获取包名：从宏包的 CTAN 页面 `ctan.org/pkg/<package name>` 查看 texlive 收录它时的包名（通常就是 `xxx.sty` 文件里的 `xxx`，有特例）
   - 搜索包名：在第一步的文件列表里搜索包名
   - 搜索的是一个宏包/字体包：以 `pgf` 包为例，能搜到 `pgf.tar.xz`、`pgf.source.tar.xz`、`pgf.code.tar.xz` 三个文件，分别对应宏包文件（必装）、源码（如 `dtx` 文件，可选安装）和文档（readme、pdf 文档，可选安装）。有的包没有 `xxx.source.tar.xz`，例如 `hlist`
   - 搜索的是一个提供可执行文件的包：可能搜到很多个文件，每个对应不同的系统，例如 `xetex`。
      - 如果本地已安装、只需要更新，执行 `tlmgr info --only-installed | grep 'xetex'` 的结果中就包含了带系统信息的包名
     - 如果本地没安装、需要的是安装新包，需要读懂系统名。 （可以使用上一条的命令，输出其他已安装的同类型包的信息，以此作为辅助信息）
1. 如何安装：手册中已记录

------

考虑到这一部分的内容较长、是较少遇到的情况、与操作系统几乎无关（`grep` 可以不用，靠肉眼观察），可以把它移放到附录，免去维护四份描述的麻烦。

**Comment by OsbertWang** [comment]
好主意，我已经开始更正，今天完成初稿

**Comment by muzimuzhi** [comment]
closed by commits https://github.com/OsbertWang/install-latex/commit/4403ec7428bd15c771deb42c1ee9d5bfb08a6589 and https://github.com/OsbertWang/install-latex/commit/5c3b817f95f2fe90f7b14f8e742a029df8cdad03
