### ISSUE TITLE
修改建议：建议补充更新指定宏包的写法

### ISSUE THREAD

**Issue by muyuuuu** [OsbertWang/install-latex#11]
![image](https://user-images.githubusercontent.com/43681138/75165015-b005cf80-575c-11ea-88ed-e635eed66e03.png)

对于我这种『只读过Lshort』的用户而言，显然不是高级用户，可能也想知道只更新一个宏包如何去写。因为我发现，尽管在对网络状态比较自信的情况下，更新的时间还是有点不想等。毕竟有的宏包更不更新，对我目前的使用来说影响不大。

![image](https://user-images.githubusercontent.com/43681138/75165210-007d2d00-575d-11ea-84b5-68b1069fa2d6.png)

**Comment by OsbertWang** [comment]
升级特定包的方法并没有写入 install-latex 是因为初级用户无法判定包之间的依赖关系。很多包需要其他包升级到特定日期之后才能正常使用。我个人就曾遇到过因其中某个包（显然它不是我显示调用的）未正常升级导致另一包（我显示调用的）无法正常通过编译。

**Comment by stone-zeng** [comment]
补充一点，tlmgr 参数中的「宏包名」与 `\usepackage` 里面的宏包名不是一个东西，虽然很多时候是一样的。前者是在 CTAN 注册、TeX Live 使用的名字（Contained in TeX Live as xxx），后者则是 `xxx.sty` 的文件名（前半段）。

**Comment by muzimuzhi** [comment]
@muyuuuu 
> 对于我这种『只读过Lshort』的用户而言，显然不是高级用户，可能也想知道只更新一个宏包如何去写。

 - 对应文档：打开 `texdoc tlmgr`，搜索 `update [option`
 - 对于「不知道 texlive 中的包名」的情况，可以去对应的 `ctan.org/pkg/<pkg name>` 页面看 "Contained in TeX Live as <pkg name>" 的信息，参考 https://zhuanlan.zhihu.com/p/43981639 ，宏包的名字一节；也可以执行 `tlmgr info xxx.sty` 查看

@stone-zeng 
> 前者是在 CTAN 注册、TeX Live 使用的名字（Contained in TeX Live as xxx）

这个也有特例，见 https://zhuanlan.zhihu.com/p/65122008

**Comment by muzimuzhi** [comment]
> 很多包需要其他包升级到特定日期之后才能正常使用。

 - 这种情况不常发生，所以我没有被这个理由说服。
 - 当前 issue 的需求已经触及 install-latex 项目的边界，安装和使用应有一定区分。所以我也支持不添加到当前项目。
texlive、latex2e 和各宏包的维护者在努力促成每年的 texlive 镜像安装后直接能用、不包含影响使用的重大 bug。如果这个目标失败了，那么目前介绍的 `tlmgr update --self --all` 已经够用了。
 - 需求是掐不断的，可以有另一份 use-texlive 来匹配它们。
