### ISSUE TITLE
对 5.3 节一些疑问

### ISSUE THREAD

**Issue by kexplorning** [OsbertWang/install-latex#15]
5.3 节里面有写

> 在 WSL 中添加窗口化插件

这是什么意思？

是安装图形界面（GUI）的意思吗？

**Comment by OsbertWang** [comment]
是的。我搜过一次，好像主要用 X Server，包括 Xming，VcXsrv，Xmanager

**Comment by syvshc** [comment]
我安装过一次X server，体验极差，甚至不如分配了1G内存的Ubuntu虚拟机

**Comment by kexplorning** [comment]
对，其实可以用了，只要把图形界面（X Windows）在系统里面安装了，然后把上面软件其中之一安装在 Windows 中，这是可以用的。而且其中 VcXsrv 是开源的。

问题是，WSL 系统太慢了，速度完全比不上双系统，这就导致图形界面异常卡顿。包括编译 TeX 文档也是，慢很多。。而且不支持 GPU。。

WSL 2 似乎好了很多，但是它依然在开发中，现在是测试版，已经可以用了，并且修复了很多奇怪 bug。。

所以解这个问题，目前比较好的做法是，不用图形界面，只用命令行界面。。

而且，VSCode + Remote WSL + LaTeX Worshop 还是很舒服的。不过，就那个编译链配置有点难为新手。。

**Comment by OsbertWang** [comment]
我没有在 install-latex 中详细地展开这个事情。
从我个人出发，texstudio 并不适合在 WSL 中使用。我自己就配置了2个按钮，引入 WSL 中的 texlive 编译一些简单的 MWE。
像 install-latex 这样的东西，我一般拿 vscode 来做，好像手册里写过这点。

**Comment by kexplorning** [comment]
嗯，我好像看到了。

只是建议改一下描述

> 这个问题的一个可选择解决方案是在 WSL 中安装图形界面并使用 X Server，这样可直接 TeXstudio 和阅读器安装至 WSL，然而该方案非常卡顿。更好的解决方案，有待微软填坑。（或者使用 VSCode）

大致这个意思。

**Comment by OsbertWang** [comment]
可以啊，这个描述比我以前那个好。
这手册有很多地方，自它初稿写完后就没再改过。
其实也是我没再看过……

**Comment by kexplorning** [comment]
最近发现一份 VSCode 配置 LaTeX 的指南：https://github.com/EthanDeng/vscode-latex

似乎可以给个链接之类的。但是感觉写得有点简单了。。

**Comment by OsbertWang** [comment]
你点击过摘要里的链接吗？

**Comment by kexplorning** [comment]
抱歉。已经加上去了。。

**Comment by OsbertWang** [comment]
此处内容已添加至 install-latex
待更新后关闭此 issue
