### ISSUE TITLE
可以考虑使用海洋大师的latexmkrc脚本用latexmk编译install-LaTeX

### ISSUE THREAD

**Issue by registor** [OsbertWang/install-latex#16]
$pdf_mode = 5;
$pdflatex = 'pdflatex -file-line-error -interaction=errorstopmode -shell-escape %O %S';
$xelatex = 'xelatex -file-line-error -interaction=errorstopmode -no-pdf -shell-escape %O %S';
$xdvipdfmx = 'xdvipdfmx -q -E -o %D %O %S';
$bibtex_use = 1.5;
$force_mode = 1;
$go_mode = 1;
$clean_ext = 'synctex.gz acn acr snm alg aux bbl xdv bcf nav blg brf fdb_latexmk glg glo gls idx ilg ind ist lof log lot out run.xml toc dvi';

add_cus_dep('glo', 'gls', 0, 'glo2gls');
sub glo2gls {
    system("makeindex -s gglo.ist -o \"$_[0].gls\" \"$_[0].glo\"");
}
push @generated_exts, "glo", "gls";

add_cus_dep('nlo', 'nls', 0, 'nlo2nls');
sub nlo2nls {
    system("makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"");
}
push @generated_exts, "nlo", "nls";

**Comment by stone-zeng** [comment]
install-latex 结构比较简单，没有索引什么的，直接用 `latexmk -xelatex main` 就可以了。

**Comment by OsbertWang** [comment]
我考虑了一下，`latexmkrc.` 倒不必写，因为都是一些默认的东西，告诉用户直接执行 `latexmk -xelatex -synctex=1 main` 就可以了。我自己尝试写了 `make.bat` 和 `makefile` 两个文件，感兴趣帮忙看一下吧。
